services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - custom_network
  
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static_volume:/myproject/staticfiles
    networks:
      - custom_network

volumes:
  postgres_data:
  static_volume:

networks:
  custom_network:
    name: custom_network