version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
    ports:
      - 5432:5432
  
  backend:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data: