# Generated by Django 5.1.1 on 2024-09-24 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of last update')),
                ('title', models.CharField(db_index=True, help_text='Title of the task.', max_length=150, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Description of the task (detailed explanation).', null=True, verbose_name='Description')),
                ('status', models.IntegerField(choices=[(1, 'Done'), (2, 'In progress'), (3, 'Planned'), (4, 'Cancelled')], default=3, help_text='Status of the task.', verbose_name='Status')),
                ('owner', models.ForeignKey(help_text='Owner of the task.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
