# Generated by Django 5.1.1 on 2024-12-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ('-updated_at',), 'verbose_name': 'User address', 'verbose_name_plural': 'User addresses'},
        ),
    ]
