# Generated by Django 5.1.1 on 2024-12-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_useraddress_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'On the way'), (3, 'Closed')], default=0, verbose_name='Order status'),
        ),
    ]
